services:
  - type: web
    name: powerdemand-backend
    runtime: python
    buildCommand: cd electricity-demand/backend && pip install -r requirements.txt
    startCommand: cd electricity-demand/backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
